insert into barcode (id, code, jhi_type, description) values (1, 1065905121, null, 'Proin interdum mauris non ligula pellentesque ultrices.');
insert into barcode (id, code, jhi_type, description) values (2, 437130425, null, 'Maecenas tincidunt lacus at velit.');
insert into barcode (id, code, jhi_type, description) values (3, 44151946, null, 'Proin at turpis a pede posuere nonummy.');
insert into barcode (id, code, jhi_type, description) values (4, 553272916, null, 'Nam nulla.');
insert into barcode (id, code, jhi_type, description) values (5, 1193504497, null, 'Aliquam quis turpis eget elit sodales scelerisque.');
insert into barcode (id, code, jhi_type, description) values (6, 674157818, null, 'Maecenas tincidunt lacus at velit.');
insert into barcode (id, code, jhi_type, description) values (7, 969525259, null, 'Duis bibendum.');
insert into barcode (id, code, jhi_type, description) values (8, 1185980593, null, 'Suspendisse potenti.');
insert into barcode (id, code, jhi_type, description) values (9, 234976619, null, 'Aenean fermentum.');
insert into barcode (id, code, jhi_type, description) values (10, 629135359, null, 'Nulla ut erat id mauris vulputate elementum.');
insert into barcode (id, code, jhi_type, description) values (11, 474453909, null, 'Duis aliquam convallis nunc.');
insert into barcode (id, code, jhi_type, description) values (12, 304843018, null, 'Phasellus sit amet erat.');
insert into barcode (id, code, jhi_type, description) values (13, 1066941818, null, 'Sed ante.');
insert into barcode (id, code, jhi_type, description) values (14, 156436516, null, 'Donec ut dolor.');
insert into barcode (id, code, jhi_type, description) values (15, 710426740, null, 'Nulla tempus.');
insert into barcode (id, code, jhi_type, description) values (16, 551938586, null, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.');
insert into barcode (id, code, jhi_type, description) values (17, 1146471892, null, 'In eleifend quam a odio.');
insert into barcode (id, code, jhi_type, description) values (18, 344369636, null, 'Maecenas tincidunt lacus at velit.');
insert into barcode (id, code, jhi_type, description) values (19, 275470635, null, 'Etiam pretium iaculis justo.');
insert into barcode (id, code, jhi_type, description) values (20, 403375766, null, 'Aliquam non mauris.');
insert into barcode (id, code, jhi_type, description) values (21, 1024979174, null, 'Duis aliquam convallis nunc.');
insert into barcode (id, code, jhi_type, description) values (22, 44009265, null, 'Quisque id justo sit amet sapien dignissim vestibulum.');
insert into barcode (id, code, jhi_type, description) values (23, 847117244, null, 'Aliquam quis turpis eget elit sodales scelerisque.');
insert into barcode (id, code, jhi_type, description) values (24, 155259482, null, 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.');
insert into barcode (id, code, jhi_type, description) values (25, 1174601220, null, 'Nullam porttitor lacus at turpis.');
insert into barcode (id, code, jhi_type, description) values (26, 34499778, null, 'Sed vel enim sit amet nunc viverra dapibus.');
insert into barcode (id, code, jhi_type, description) values (27, 587497189, null, 'Duis aliquam convallis nunc.');
insert into barcode (id, code, jhi_type, description) values (28, 981327023, null, 'In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into barcode (id, code, jhi_type, description) values (29, 1010980131, null, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into barcode (id, code, jhi_type, description) values (30, 418320995, null, 'Cras non velit nec nisi vulputate nonummy.');
insert into barcode (id, code, jhi_type, description) values (31, 1171545615, null, 'Morbi a ipsum.');
insert into barcode (id, code, jhi_type, description) values (32, 188864667, null, 'Etiam faucibus cursus urna.');
insert into barcode (id, code, jhi_type, description) values (33, 1227902754, null, 'Morbi porttitor lorem id ligula.');
insert into barcode (id, code, jhi_type, description) values (34, 829290700, null, 'Suspendisse potenti.');
insert into barcode (id, code, jhi_type, description) values (35, 575875015, null, 'Integer tincidunt ante vel ipsum.');
insert into barcode (id, code, jhi_type, description) values (36, 487675920, null, 'Proin interdum mauris non ligula pellentesque ultrices.');
insert into barcode (id, code, jhi_type, description) values (37, 811862592, null, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.');
insert into barcode (id, code, jhi_type, description) values (38, 1113266565, null, 'In quis justo.');
insert into barcode (id, code, jhi_type, description) values (39, 87182155, null, 'Maecenas rhoncus aliquam lacus.');
insert into barcode (id, code, jhi_type, description) values (40, 793946275, null, 'Mauris ullamcorper purus sit amet nulla.');
insert into barcode (id, code, jhi_type, description) values (41, 1035988318, null, 'Proin eu mi.');
insert into barcode (id, code, jhi_type, description) values (42, 1174687032, null, 'Donec quis orci eget orci vehicula condimentum.');
insert into barcode (id, code, jhi_type, description) values (43, 828533631, null, 'In hac habitasse platea dictumst.');
insert into barcode (id, code, jhi_type, description) values (44, 144551848, null, 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into barcode (id, code, jhi_type, description) values (45, 442676097, null, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.');
insert into barcode (id, code, jhi_type, description) values (46, 596660337, null, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.');
insert into barcode (id, code, jhi_type, description) values (47, 978380126, null, 'Integer a nibh.');
insert into barcode (id, code, jhi_type, description) values (48, 531686320, null, 'Donec ut mauris eget massa tempor convallis.');
insert into barcode (id, code, jhi_type, description) values (49, 1102900906, null, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.');
insert into barcode (id, code, jhi_type, description) values (50, 920230468, null, 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
insert into barcode (id, code, jhi_type, description) values (51, 817768192, null, 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into barcode (id, code, jhi_type, description) values (52, 86641205, null, 'Morbi a ipsum.');
insert into barcode (id, code, jhi_type, description) values (53, 1127040896, null, 'Cras in purus eu magna vulputate luctus.');
insert into barcode (id, code, jhi_type, description) values (54, 788691374, null, 'Curabitur at ipsum ac tellus semper interdum.');
insert into barcode (id, code, jhi_type, description) values (55, 978157268, null, 'Duis mattis egestas metus.');
insert into barcode (id, code, jhi_type, description) values (56, 440874622, null, 'Cras non velit nec nisi vulputate nonummy.');
insert into barcode (id, code, jhi_type, description) values (57, 1000598790, null, 'Pellentesque at nulla.');
insert into barcode (id, code, jhi_type, description) values (58, 895777990, null, 'Suspendisse potenti.');
insert into barcode (id, code, jhi_type, description) values (59, 705879913, null, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.');
insert into barcode (id, code, jhi_type, description) values (60, 1152696747, null, 'Proin at turpis a pede posuere nonummy.');
insert into barcode (id, code, jhi_type, description) values (61, 282645893, null, 'Integer non velit.');
insert into barcode (id, code, jhi_type, description) values (62, 111772984, null, 'Suspendisse ornare consequat lectus.');
insert into barcode (id, code, jhi_type, description) values (63, 33298331, null, 'Integer ac neque.');
insert into barcode (id, code, jhi_type, description) values (64, 24989917, null, 'Nulla tellus.');
insert into barcode (id, code, jhi_type, description) values (65, 694148023, null, 'Vestibulum ac est lacinia nisi venenatis tristique.');
insert into barcode (id, code, jhi_type, description) values (66, 1080443400, null, 'Vivamus vestibulum sagittis sapien.');
insert into barcode (id, code, jhi_type, description) values (67, 55835852, null, 'Proin eu mi.');
insert into barcode (id, code, jhi_type, description) values (68, 938384833, null, 'Nunc purus.');
insert into barcode (id, code, jhi_type, description) values (69, 102549238, null, 'Aliquam sit amet diam in magna bibendum imperdiet.');
insert into barcode (id, code, jhi_type, description) values (70, 805776833, null, 'Donec ut mauris eget massa tempor convallis.');
insert into barcode (id, code, jhi_type, description) values (71, 656240413, null, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into barcode (id, code, jhi_type, description) values (72, 257459545, null, 'Curabitur convallis.');
insert into barcode (id, code, jhi_type, description) values (73, 1202555971, null, 'Cras pellentesque volutpat dui.');
insert into barcode (id, code, jhi_type, description) values (74, 1106543559, null, 'Duis ac nibh.');
insert into barcode (id, code, jhi_type, description) values (75, 697594603, null, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.');
insert into barcode (id, code, jhi_type, description) values (76, 292173314, null, 'In eleifend quam a odio.');
insert into barcode (id, code, jhi_type, description) values (77, 743545462, null, 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into barcode (id, code, jhi_type, description) values (78, 809114258, null, 'Morbi vel lectus in quam fringilla rhoncus.');
insert into barcode (id, code, jhi_type, description) values (79, 921103127, null, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.');
insert into barcode (id, code, jhi_type, description) values (80, 282576439, null, 'Morbi quis tortor id nulla ultrices aliquet.');
insert into barcode (id, code, jhi_type, description) values (81, 635820635, null, 'Aliquam erat volutpat.');
insert into barcode (id, code, jhi_type, description) values (82, 670706388, null, 'Fusce posuere felis sed lacus.');
insert into barcode (id, code, jhi_type, description) values (83, 799409460, null, 'Etiam faucibus cursus urna.');
insert into barcode (id, code, jhi_type, description) values (84, 103413037, null, 'Vivamus vestibulum sagittis sapien.');
insert into barcode (id, code, jhi_type, description) values (85, 961154770, null, 'Etiam vel augue.');
insert into barcode (id, code, jhi_type, description) values (86, 191832814, null, 'Pellentesque ultrices mattis odio.');
insert into barcode (id, code, jhi_type, description) values (87, 1146784576, null, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into barcode (id, code, jhi_type, description) values (88, 992615862, null, 'Morbi porttitor lorem id ligula.');
insert into barcode (id, code, jhi_type, description) values (89, 963647490, null, 'Nunc purus.');
insert into barcode (id, code, jhi_type, description) values (90, 491006776, null, 'Donec posuere metus vitae ipsum.');
insert into barcode (id, code, jhi_type, description) values (91, 271867012, null, 'Maecenas tincidunt lacus at velit.');
insert into barcode (id, code, jhi_type, description) values (92, 389405077, null, 'Suspendisse accumsan tortor quis turpis.');
insert into barcode (id, code, jhi_type, description) values (93, 936042580, null, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.');
insert into barcode (id, code, jhi_type, description) values (94, 49923910, null, 'Pellentesque eget nunc.');
insert into barcode (id, code, jhi_type, description) values (95, 486592564, null, 'Etiam vel augue.');
insert into barcode (id, code, jhi_type, description) values (96, 429836658, null, 'In eleifend quam a odio.');
insert into barcode (id, code, jhi_type, description) values (97, 974914656, null, 'In eleifend quam a odio.');
insert into barcode (id, code, jhi_type, description) values (98, 968729736, null, 'Aliquam quis turpis eget elit sodales scelerisque.');
insert into barcode (id, code, jhi_type, description) values (99, 1078340220, null, 'Aliquam non mauris.');
insert into barcode (id, code, jhi_type, description) values (100, 1171183543, null, 'Ut tellus.');
