insert into label (id, name, description) values (1, 'cursus', 'Quisque ut erat.');
insert into label (id, name, description) values (2, 'posuere', 'Sed accumsan felis.');
insert into label (id, name, description) values (3, 'justo', 'Donec posuere metus vitae ipsum.');
insert into label (id, name, description) values (4, 'justo', 'Pellentesque at nulla.');
insert into label (id, name, description) values (5, 'massa', 'In eleifend quam a odio.');
insert into label (id, name, description) values (6, 'elit', 'Donec ut mauris eget massa tempor convallis.');
insert into label (id, name, description) values (7, 'elementum', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.');
insert into label (id, name, description) values (8, 'parturient', 'Proin interdum mauris non ligula pellentesque ultrices.');
insert into label (id, name, description) values (9, 'sapien', 'Pellentesque at nulla.');
insert into label (id, name, description) values (10, 'volutpat', 'Vivamus in felis eu sapien cursus vestibulum.');
insert into label (id, name, description) values (11, 'nunc', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.');
insert into label (id, name, description) values (12, 'montes', 'Morbi ut odio.');
insert into label (id, name, description) values (13, 'turpis', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.');
insert into label (id, name, description) values (14, 'ut', 'Duis bibendum.');
insert into label (id, name, description) values (15, 'eu', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into label (id, name, description) values (16, 'eu', 'Donec vitae nisi.');
insert into label (id, name, description) values (17, 'aliquam', 'Donec ut dolor.');
insert into label (id, name, description) values (18, 'cursus', 'Vestibulum ac est lacinia nisi venenatis tristique.');
insert into label (id, name, description) values (19, 'praesent', 'In blandit ultrices enim.');
insert into label (id, name, description) values (20, 'leo', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
insert into label (id, name, description) values (21, 'ut', 'Quisque id justo sit amet sapien dignissim vestibulum.');
insert into label (id, name, description) values (22, 'morbi', 'Maecenas ut massa quis augue luctus tincidunt.');
insert into label (id, name, description) values (23, 'congue', 'Nunc rhoncus dui vel sem.');
insert into label (id, name, description) values (24, 'accumsan', 'Etiam pretium iaculis justo.');
insert into label (id, name, description) values (25, 'id', 'Cras pellentesque volutpat dui.');
insert into label (id, name, description) values (26, 'sit', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.');
insert into label (id, name, description) values (27, 'tempus', 'Praesent blandit.');
insert into label (id, name, description) values (28, 'aenean', 'Vivamus in felis eu sapien cursus vestibulum.');
insert into label (id, name, description) values (29, 'turpis', 'Proin interdum mauris non ligula pellentesque ultrices.');
insert into label (id, name, description) values (30, 'erat', 'Integer non velit.');
insert into label (id, name, description) values (31, 'ridiculus', 'Maecenas rhoncus aliquam lacus.');
insert into label (id, name, description) values (32, 'convallis', 'Donec posuere metus vitae ipsum.');
insert into label (id, name, description) values (33, 'nulla', 'Donec semper sapien a libero.');
insert into label (id, name, description) values (34, 'luctus', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into label (id, name, description) values (35, 'sit', 'Aenean fermentum.');
insert into label (id, name, description) values (36, 'nonummy', 'Sed ante.');
insert into label (id, name, description) values (37, 'integer', 'Vivamus tortor.');
insert into label (id, name, description) values (38, 'condimentum', 'Nunc rhoncus dui vel sem.');
insert into label (id, name, description) values (39, 'libero', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.');
insert into label (id, name, description) values (40, 'dapibus', 'Nullam varius.');
insert into label (id, name, description) values (41, 'vivamus', 'Donec dapibus.');
insert into label (id, name, description) values (42, 'curae', 'Suspendisse accumsan tortor quis turpis.');
insert into label (id, name, description) values (43, 'eget', 'Vivamus in felis eu sapien cursus vestibulum.');
insert into label (id, name, description) values (44, 'turpis', 'Nam tristique tortor eu pede.');
insert into label (id, name, description) values (45, 'scelerisque', 'In sagittis dui vel nisl.');
insert into label (id, name, description) values (46, 'integer', 'Donec vitae nisi.');
insert into label (id, name, description) values (47, 'varius', 'Etiam justo.');
insert into label (id, name, description) values (48, 'eget', 'Phasellus sit amet erat.');
insert into label (id, name, description) values (49, 'ut', 'Suspendisse accumsan tortor quis turpis.');
insert into label (id, name, description) values (50, 'iaculis', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.');
insert into label (id, name, description) values (51, 'sed', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.');
insert into label (id, name, description) values (52, 'morbi', 'Nulla ac enim.');
insert into label (id, name, description) values (53, 'risus', 'Quisque id justo sit amet sapien dignissim vestibulum.');
insert into label (id, name, description) values (54, 'praesent', 'Aliquam non mauris.');
insert into label (id, name, description) values (55, 'pede', 'Aliquam quis turpis eget elit sodales scelerisque.');
insert into label (id, name, description) values (56, 'rhoncus', 'Integer ac neque.');
insert into label (id, name, description) values (57, 'a', 'Duis at velit eu est congue elementum.');
insert into label (id, name, description) values (58, 'nullam', 'Maecenas pulvinar lobortis est.');
insert into label (id, name, description) values (59, 'at', 'Donec quis orci eget orci vehicula condimentum.');
insert into label (id, name, description) values (60, 'imperdiet', 'Duis aliquam convallis nunc.');
insert into label (id, name, description) values (61, 'auctor', 'Nullam varius.');
insert into label (id, name, description) values (62, 'nec', 'Donec dapibus.');
insert into label (id, name, description) values (63, 'orci', 'Nunc rhoncus dui vel sem.');
insert into label (id, name, description) values (64, 'et', 'Duis at velit eu est congue elementum.');
insert into label (id, name, description) values (65, 'lectus', 'Sed sagittis.');
insert into label (id, name, description) values (66, 'eu', 'Suspendisse potenti.');
insert into label (id, name, description) values (67, 'elit', 'Nullam molestie nibh in lectus.');
insert into label (id, name, description) values (68, 'ante', 'In hac habitasse platea dictumst.');
insert into label (id, name, description) values (69, 'quisque', 'Vivamus vestibulum sagittis sapien.');
insert into label (id, name, description) values (70, 'quis', 'Morbi a ipsum.');
insert into label (id, name, description) values (71, 'fusce', 'Suspendisse potenti.');
insert into label (id, name, description) values (72, 'congue', 'Quisque ut erat.');
insert into label (id, name, description) values (73, 'nibh', 'Aenean auctor gravida sem.');
insert into label (id, name, description) values (74, 'orci', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into label (id, name, description) values (75, 'lorem', 'Pellentesque ultrices mattis odio.');
insert into label (id, name, description) values (76, 'volutpat', 'Duis bibendum.');
insert into label (id, name, description) values (77, 'augue', 'Morbi non lectus.');
insert into label (id, name, description) values (78, 'odio', 'Vivamus tortor.');
insert into label (id, name, description) values (79, 'sed', 'Vestibulum sed magna at nunc commodo placerat.');
insert into label (id, name, description) values (80, 'sed', 'Mauris sit amet eros.');
insert into label (id, name, description) values (81, 'integer', 'Fusce posuere felis sed lacus.');
insert into label (id, name, description) values (82, 'eget', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.');
insert into label (id, name, description) values (83, 'nulla', 'Mauris sit amet eros.');
insert into label (id, name, description) values (84, 'congue', 'Nullam varius.');
insert into label (id, name, description) values (85, 'pretium', 'In congue.');
insert into label (id, name, description) values (86, 'nisl', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.');
insert into label (id, name, description) values (87, 'parturient', 'Pellentesque ultrices mattis odio.');
insert into label (id, name, description) values (88, 'tempor', 'Maecenas ut massa quis augue luctus tincidunt.');
insert into label (id, name, description) values (89, 'justo', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.');
insert into label (id, name, description) values (90, 'nunc', 'Integer non velit.');
insert into label (id, name, description) values (91, 'adipiscing', 'Morbi ut odio.');
insert into label (id, name, description) values (92, 'consectetuer', 'Nam tristique tortor eu pede.');
insert into label (id, name, description) values (93, 'ipsum', 'Etiam pretium iaculis justo.');
insert into label (id, name, description) values (94, 'vulputate', 'Nunc purus.');
insert into label (id, name, description) values (95, 'semper', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.');
insert into label (id, name, description) values (96, 'eros', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.');
insert into label (id, name, description) values (97, 'fermentum', 'Nulla facilisi.');
insert into label (id, name, description) values (98, 'tellus', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.');
insert into label (id, name, description) values (99, 'ut', 'Maecenas rhoncus aliquam lacus.');
insert into label (id, name, description) values (100, 'ipsum', 'Nulla mollis molestie lorem.');
