insert into status (id, reference, name, description) values (1, 1969, 'middleware', 'Suspendisse potenti.');
insert into status (id, reference, name, description) values (2, 1002, 'portal', 'Vestibulum ac est lacinia nisi venenatis tristique.');
insert into status (id, reference, name, description) values (3, 1588, 'flexibility', 'Curabitur convallis.');
insert into status (id, reference, name, description) values (4, 1888, 'non-volatile', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into status (id, reference, name, description) values (5, 1229, 'bi-directional', 'Etiam pretium iaculis justo.');
insert into status (id, reference, name, description) values (6, 1076, 'secured line', 'In congue.');
insert into status (id, reference, name, description) values (7, 1538, 'hybrid', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
insert into status (id, reference, name, description) values (8, 1873, 'frame', 'Cras non velit nec nisi vulputate nonummy.');
insert into status (id, reference, name, description) values (9, 1553, 'asymmetric', 'Mauris sit amet eros.');
insert into status (id, reference, name, description) values (10, 1367, 'collaboration', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.');
insert into status (id, reference, name, description) values (11, 1350, 'Function-based', 'Curabitur in libero ut massa volutpat convallis.');
insert into status (id, reference, name, description) values (12, 1400, 'encoding', 'Sed ante.');
insert into status (id, reference, name, description) values (13, 1907, 'directional', 'Proin interdum mauris non ligula pellentesque ultrices.');
insert into status (id, reference, name, description) values (14, 1364, 'Diverse', 'Cras in purus eu magna vulputate luctus.');
insert into status (id, reference, name, description) values (15, 1500, 'middleware', 'Pellentesque at nulla.');
insert into status (id, reference, name, description) values (16, 1126, 'task-force', 'Aenean auctor gravida sem.');
insert into status (id, reference, name, description) values (17, 1357, 'focus group', 'Suspendisse ornare consequat lectus.');
insert into status (id, reference, name, description) values (18, 1579, 'website', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.');
insert into status (id, reference, name, description) values (19, 1984, 'incremental', 'Nam tristique tortor eu pede.');
insert into status (id, reference, name, description) values (20, 1759, 'Programmable', 'Nullam varius.');
insert into status (id, reference, name, description) values (21, 1518, 'Secured', 'Morbi porttitor lorem id ligula.');
insert into status (id, reference, name, description) values (22, 1795, 'explicit', 'Suspendisse accumsan tortor quis turpis.');
insert into status (id, reference, name, description) values (23, 1380, 'matrix', 'Proin eu mi.');
insert into status (id, reference, name, description) values (24, 1833, 'clear-thinking', 'Vivamus in felis eu sapien cursus vestibulum.');
insert into status (id, reference, name, description) values (25, 1613, 'uniform', 'Morbi ut odio.');
insert into status (id, reference, name, description) values (26, 1604, 'Adaptive', 'In congue.');
insert into status (id, reference, name, description) values (27, 1912, '24/7', 'Morbi quis tortor id nulla ultrices aliquet.');
insert into status (id, reference, name, description) values (28, 1788, 'Automated', 'Integer tincidunt ante vel ipsum.');
insert into status (id, reference, name, description) values (29, 1724, 'background', 'Vivamus vestibulum sagittis sapien.');
insert into status (id, reference, name, description) values (30, 1500, 'Assimilated', 'Praesent id massa id nisl venenatis lacinia.');
insert into status (id, reference, name, description) values (31, 1503, 'Graphic Interface', 'Suspendisse ornare consequat lectus.');
insert into status (id, reference, name, description) values (32, 1311, 'fault-tolerant', 'Maecenas pulvinar lobortis est.');
insert into status (id, reference, name, description) values (33, 1905, 'Virtual', 'In blandit ultrices enim.');
insert into status (id, reference, name, description) values (34, 1920, 'Upgradable', 'Nunc nisl.');
insert into status (id, reference, name, description) values (35, 1452, 'Cloned', 'Ut tellus.');
insert into status (id, reference, name, description) values (36, 1754, 'Future-proofed', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.');
insert into status (id, reference, name, description) values (37, 1115, 'modular', 'Pellentesque viverra pede ac diam.');
insert into status (id, reference, name, description) values (38, 1061, 'open system', 'Nulla tellus.');
insert into status (id, reference, name, description) values (39, 1965, 'flexibility', 'In sagittis dui vel nisl.');
insert into status (id, reference, name, description) values (40, 1531, 'non-volatile', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.');
insert into status (id, reference, name, description) values (41, 1392, 'Inverse', 'Phasellus sit amet erat.');
insert into status (id, reference, name, description) values (42, 1011, 'analyzing', 'In hac habitasse platea dictumst.');
insert into status (id, reference, name, description) values (43, 1091, 'tangible', 'Duis mattis egestas metus.');
insert into status (id, reference, name, description) values (44, 1771, 'ability', 'Etiam pretium iaculis justo.');
insert into status (id, reference, name, description) values (45, 1077, 'Up-sized', 'Nunc nisl.');
insert into status (id, reference, name, description) values (46, 1039, 'framework', 'Nunc purus.');
insert into status (id, reference, name, description) values (47, 1536, 'scalable', 'Curabitur in libero ut massa volutpat convallis.');
insert into status (id, reference, name, description) values (48, 1843, 'Intuitive', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into status (id, reference, name, description) values (49, 1445, 'ability', 'In eleifend quam a odio.');
insert into status (id, reference, name, description) values (50, 1451, 'demand-driven', 'Praesent blandit lacinia erat.');
insert into status (id, reference, name, description) values (51, 1731, 'hardware', 'Proin risus.');
insert into status (id, reference, name, description) values (52, 1200, 'Re-engineered', 'Quisque porta volutpat erat.');
insert into status (id, reference, name, description) values (53, 1616, 'task-force', 'Aliquam non mauris.');
insert into status (id, reference, name, description) values (54, 1088, 'Monitored', 'Praesent blandit lacinia erat.');
insert into status (id, reference, name, description) values (55, 1669, 'interactive', 'In hac habitasse platea dictumst.');
insert into status (id, reference, name, description) values (56, 1384, 'collaboration', 'Etiam vel augue.');
insert into status (id, reference, name, description) values (57, 1490, 'Progressive', 'In hac habitasse platea dictumst.');
insert into status (id, reference, name, description) values (58, 1444, 'systemic', 'Praesent id massa id nisl venenatis lacinia.');
insert into status (id, reference, name, description) values (59, 1979, 'migration', 'Etiam pretium iaculis justo.');
insert into status (id, reference, name, description) values (60, 1539, 'regional', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.');
insert into status (id, reference, name, description) values (61, 1482, 'capability', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.');
insert into status (id, reference, name, description) values (62, 1466, 'human-resource', 'Pellentesque at nulla.');
insert into status (id, reference, name, description) values (63, 1129, 'object-oriented', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.');
insert into status (id, reference, name, description) values (64, 1321, 'Organized', 'Morbi non lectus.');
insert into status (id, reference, name, description) values (65, 1123, 'open architecture', 'Vivamus vestibulum sagittis sapien.');
insert into status (id, reference, name, description) values (66, 1019, 'algorithm', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.');
insert into status (id, reference, name, description) values (67, 1067, 'bifurcated', 'Praesent blandit.');
insert into status (id, reference, name, description) values (68, 1357, 'success', 'Quisque ut erat.');
insert into status (id, reference, name, description) values (69, 1334, 'structure', 'Maecenas pulvinar lobortis est.');
insert into status (id, reference, name, description) values (70, 1083, 'Optimized', 'Duis at velit eu est congue elementum.');
insert into status (id, reference, name, description) values (71, 1764, 'function', 'Pellentesque at nulla.');
insert into status (id, reference, name, description) values (72, 1609, 'success', 'Etiam justo.');
insert into status (id, reference, name, description) values (73, 1669, 'concept', 'Morbi quis tortor id nulla ultrices aliquet.');
insert into status (id, reference, name, description) values (74, 1503, 'local area network', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.');
insert into status (id, reference, name, description) values (75, 1866, 'actuating', 'Mauris lacinia sapien quis libero.');
insert into status (id, reference, name, description) values (76, 1331, 'heuristic', 'Nam nulla.');
insert into status (id, reference, name, description) values (77, 1326, 'methodology', 'Nullam molestie nibh in lectus.');
insert into status (id, reference, name, description) values (78, 1007, 'grid-enabled', 'Aliquam erat volutpat.');
insert into status (id, reference, name, description) values (79, 1594, '4th generation', 'Maecenas pulvinar lobortis est.');
insert into status (id, reference, name, description) values (80, 1124, 'Secured', 'Proin at turpis a pede posuere nonummy.');
insert into status (id, reference, name, description) values (81, 1266, 'Decentralized', 'Morbi non lectus.');
insert into status (id, reference, name, description) values (82, 1895, 'Open-architected', 'Vestibulum ac est lacinia nisi venenatis tristique.');
insert into status (id, reference, name, description) values (83, 1964, 'hierarchy', 'Nullam varius.');
insert into status (id, reference, name, description) values (84, 1634, '6th generation', 'Praesent lectus.');
insert into status (id, reference, name, description) values (85, 1487, 'Re-contextualized', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
insert into status (id, reference, name, description) values (86, 1457, 'Persistent', 'Morbi quis tortor id nulla ultrices aliquet.');
insert into status (id, reference, name, description) values (87, 1028, 'capability', 'Sed ante.');
insert into status (id, reference, name, description) values (88, 1333, 'hybrid', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.');
insert into status (id, reference, name, description) values (89, 1601, 'open system', 'Donec posuere metus vitae ipsum.');
insert into status (id, reference, name, description) values (90, 1358, 'contingency', 'Morbi a ipsum.');
insert into status (id, reference, name, description) values (91, 1503, 'Devolved', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into status (id, reference, name, description) values (92, 1339, 'executive', 'Mauris sit amet eros.');
insert into status (id, reference, name, description) values (93, 1112, 'moderator', 'Ut tellus.');
insert into status (id, reference, name, description) values (94, 1085, 'discrete', 'Donec vitae nisi.');
insert into status (id, reference, name, description) values (95, 1353, 'Self-enabling', 'In quis justo.');
insert into status (id, reference, name, description) values (96, 1048, 'Enhanced', 'Pellentesque eget nunc.');
insert into status (id, reference, name, description) values (97, 1577, 'migration', 'Duis bibendum.');
insert into status (id, reference, name, description) values (98, 1620, 'Balanced', 'In hac habitasse platea dictumst.');
insert into status (id, reference, name, description) values (99, 1107, 'ability', 'Morbi a ipsum.');
insert into status (id, reference, name, description) values (100, 1392, 'Up-sized', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
