insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (1, 'Pate - Cognac', 'Maecenas tincidunt lacus at velit.', 17, 'CGST', 1);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (2, 'Sugar - Crumb', 'Integer ac neque.', 23, 'SGST', 2);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (3, 'Water - Mineral, Natural', 'Cras non velit nec nisi vulputate nonummy.', 25, 'CESS', 3);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (4, 'Wine - Barbera Alba Doc 2001', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 21, 'CESS', 4);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (5, 'Dry Ice', 'Aliquam erat volutpat.', 16, 'CGST', 5);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (6, 'Gherkin - Sour', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 5, 'UGST', 6);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (7, 'Beer - Fruli', 'Aenean sit amet justo.', 23, 'CGST', 7);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (8, 'Syrup - Monin - Granny Smith', 'Ut tellus.', 12, 'SGST', 8);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (9, 'Rum - Cream, Amarula', 'Etiam vel augue.', 15, 'IGST', 9);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (10, 'Trout - Hot Smkd, Dbl Fillet', 'Morbi a ipsum.', 24, 'IGST', 10);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (11, 'Muffin Mix - Blueberry', 'Integer non velit.', 10, 'CGST', 11);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (12, 'Mushroom - Chantrelle, Fresh', 'Aliquam sit amet diam in magna bibendum imperdiet.', 18, 'CGST', 12);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (13, 'Crab - Meat Combo', 'Proin at turpis a pede posuere nonummy.', 23, 'UGST', 13);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (14, 'Flour Dark Rye', 'Sed sagittis.', 17, 'CGST', 14);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (15, 'Cookie Choc', 'Donec semper sapien a libero.', 17, 'CGST', 15);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (16, 'Arctic Char - Fillets', 'Nulla ac enim.', 25, 'UGST', 16);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (17, 'Flavouring - Raspberry', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', 13, 'SGST', 17);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (18, 'Veal - Round, Eye Of', 'Maecenas pulvinar lobortis est.', 17, 'CGST', 18);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (19, 'Cinnamon Buns Sticky', 'Duis at velit eu est congue elementum.', 23, 'CESS', 19);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (20, 'Beans - Fava, Canned', 'Sed accumsan felis.', 6, 'UGST', 20);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (21, 'Foil - 4oz Custard Cup', 'Suspendisse potenti.', 20, 'CGST', 21);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (22, 'Beans - Kidney, Canned', 'Aenean sit amet justo.', 10, 'UGST', 22);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (23, 'Soup - Campbells Chicken', 'In hac habitasse platea dictumst.', 21, 'SGST', 23);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (24, 'Pike - Frozen Fillet', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 7, 'CESS', 24);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (25, 'Couscous', 'Pellentesque at nulla.', 24, 'CESS', 25);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (26, 'Saskatoon Berries - Frozen', 'Pellentesque viverra pede ac diam.', 18, 'IGST', 26);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (27, 'Everfresh Products', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 13, 'CESS', 27);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (28, 'Vinegar - Cider', 'Quisque ut erat.', 17, 'SGST', 28);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (29, 'Arizona - Plum Green Tea', 'Mauris ullamcorper purus sit amet nulla.', 16, 'CGST', 29);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (30, 'Cake - Box Window 10x10x2.5', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', 8, 'CESS', 30);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (31, 'Tarragon - Fresh', 'Aliquam erat volutpat.', 11, 'UGST', 31);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (32, 'Goat - Whole Cut', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 14, 'IGST', 32);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (33, 'Oil - Canola', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 28, 'IGST', 33);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (34, 'Muffin - Mix - Mango Sour Cherry', 'Nulla ac enim.', 24, 'SGST', 34);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (35, 'Tart - Raisin And Pecan', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 10, 'SGST', 35);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (36, 'Coffee - Decafenated', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', 8, 'UGST', 36);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (37, 'Sprouts - Corn', 'Aliquam sit amet diam in magna bibendum imperdiet.', 13, 'IGST', 37);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (38, 'Sugar - Cubes', 'Integer ac neque.', 5, 'UGST', 38);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (39, 'Syrup - Monin - Granny Smith', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 6, 'CESS', 39);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (40, 'Chips - Assorted', 'Cras in purus eu magna vulputate luctus.', 25, 'SGST', 40);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (41, 'Bagel - Plain', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 13, 'CGST', 41);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (42, 'Cake - Night And Day Choclate', 'Nam dui.', 19, 'IGST', 42);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (43, 'Red Snapper - Fresh, Whole', 'Nunc nisl.', 20, 'CESS', 43);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (44, 'Pork - Ham Hocks - Smoked', 'Donec ut mauris eget massa tempor convallis.', 12, 'UGST', 44);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (45, 'Tarragon - Primerba, Paste', 'Aenean auctor gravida sem.', 16, 'UGST', 45);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (46, 'Pasta - Angel Hair', 'In blandit ultrices enim.', 28, 'CGST', 46);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (47, 'Squash - Butternut', 'Duis ac nibh.', 25, 'CGST', 47);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (48, 'Oil - Cooking Spray', 'In hac habitasse platea dictumst.', 20, 'CGST', 48);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (49, 'Beef Cheek Fresh', 'Aenean fermentum.', 13, 'UGST', 49);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (50, 'Lobster - Baby, Boiled', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 26, 'CESS', 50);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (51, 'Cucumber - English', 'Mauris sit amet eros.', 24, 'UGST', 51);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (52, 'Wine - White, Colubia Cresh', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 14, 'CESS', 52);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (53, 'Tea - Mint', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 20, 'CESS', 53);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (54, 'Milk - Homo', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', 23, 'IGST', 54);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (55, 'Oven Mitts 17 Inch', 'Donec posuere metus vitae ipsum.', 27, 'SGST', 55);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (56, 'Lid Coffee Cup 8oz Blk', 'Integer a nibh.', 11, 'SGST', 56);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (57, 'Pepper - Paprika, Hungarian', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 16, 'SGST', 57);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (58, 'Wine - Red, Wolf Blass, Yellow', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 18, 'CGST', 58);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (59, 'Bread - Rolls, Corn', 'Proin interdum mauris non ligula pellentesque ultrices.', 15, 'CESS', 59);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (60, 'Pepper - Chillies, Crushed', 'Aliquam erat volutpat.', 24, 'UGST', 60);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (61, 'Ice Cream Bar - Hageen Daz To', 'Vestibulum rutrum rutrum neque.', 8, 'UGST', 61);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (62, 'Potatoes - Yukon Gold 5 Oz', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', 15, 'SGST', 62);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (63, 'Lamb - Leg, Boneless', 'Morbi a ipsum.', 13, 'IGST', 63);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (64, 'Toamtoes 6x7 Select', 'Vivamus vestibulum sagittis sapien.', 5, 'CGST', 64);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (65, 'Liners - Banana, Paper', 'Nulla mollis molestie lorem.', 15, 'CGST', 65);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (66, 'Rum - Dark, Bacardi, Black', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', 14, 'IGST', 66);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (67, 'Burger Veggie', 'Nullam molestie nibh in lectus.', 22, 'IGST', 67);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (68, 'Cocoa Powder - Natural', 'Duis ac nibh.', 25, 'CGST', 68);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (69, 'Flour - Chickpea', 'Nulla ut erat id mauris vulputate elementum.', 10, 'UGST', 69);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (70, 'Beer - Creemore', 'Nulla ac enim.', 17, 'IGST', 70);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (71, 'Sambuca Cream', 'Duis consequat dui nec nisi volutpat eleifend.', 24, 'SGST', 71);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (72, 'Wine - Dubouef Macon - Villages', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 15, 'CGST', 72);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (73, 'Hickory Smoke, Liquid', 'Aenean auctor gravida sem.', 24, 'CGST', 73);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (74, 'Energy Drink Bawls', 'Nulla tempus.', 8, 'UGST', 74);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (75, 'Trout Rainbow Whole', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 17, 'CGST', 75);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (76, 'Beer - Creemore', 'Suspendisse potenti.', 19, 'IGST', 76);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (77, 'Bread - Frozen Basket Variety', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 28, 'UGST', 77);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (78, 'Lettuce - Lolla Rosa', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 10, 'SGST', 78);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (79, 'Peach - Fresh', 'Morbi non quam nec dui luctus rutrum.', 17, 'SGST', 79);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (80, 'Container - Clear 32 Oz', 'Nulla suscipit ligula in lacus.', 20, 'SGST', 80);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (81, 'Lettuce - Red Leaf', 'Mauris lacinia sapien quis libero.', 22, 'IGST', 81);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (82, 'Veal - Liver', 'In hac habitasse platea dictumst.', 13, 'CESS', 82);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (83, 'Curry Powder', 'Integer tincidunt ante vel ipsum.', 7, 'CESS', 83);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (84, 'Vegetable - Base', 'Pellentesque viverra pede ac diam.', 20, 'SGST', 84);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (85, 'Fuji Apples', 'Sed ante.', 28, 'SGST', 85);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (86, 'Pie Shell - 5', 'Maecenas ut massa quis augue luctus tincidunt.', 21, 'UGST', 86);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (87, 'Butter Balls Salted', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', 15, 'UGST', 87);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (88, 'Soup - Base Broth Beef', 'Vestibulum ac est lacinia nisi venenatis tristique.', 13, 'CGST', 88);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (89, 'Onions - Green', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', 19, 'UGST', 89);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (90, 'Steampan - Half Size Shallow', 'Morbi non quam nec dui luctus rutrum.', 15, 'UGST', 90);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (91, 'Pork - Shoulder', 'Phasellus sit amet erat.', 28, 'IGST', 91);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (92, 'Pumpkin - Seed', 'Nullam sit amet turpis elementum ligula vehicula consequat.', 9, 'CGST', 92);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (93, 'Longos - Lasagna Beef', 'Aenean lectus.', 20, 'IGST', 93);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (94, 'Yogurt - Cherry, 175 Gr', 'Vivamus tortor.', 20, 'UGST', 94);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (95, 'Crab - Blue, Frozen', 'Etiam justo.', 20, 'SGST', 95);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (96, 'Pineapple - Canned, Rings', 'Integer non velit.', 27, 'IGST', 96);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (97, 'Sugar - Invert', 'Nulla justo.', 18, 'CESS', 97);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (98, 'Napkin Colour', 'Maecenas tincidunt lacus at velit.', 6, 'CESS', 98);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (99, 'Cookie Dough - Peanut Butter', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 10, 'SGST', 99);
insert into tax (id, name, description,  rate, jhi_type,  tax_category_id) values (100, 'Lettuce - Iceberg', 'Ut tellus.', 8, 'CGST', 100);
