insert into tax_category (id, name, description) values (1, 'Nut - Macadamia', 'Sed ante.');
insert into tax_category (id, name, description) values (2, 'Sherbet - Raspberry', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.');
insert into tax_category (id, name, description) values (3, 'Wine - Sauvignon Blanc', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.');
insert into tax_category (id, name, description) values (4, 'Cheese - Mascarpone', 'Vivamus tortor.');
insert into tax_category (id, name, description) values (5, 'Sprouts - Onion', 'Aliquam quis turpis eget elit sodales scelerisque.');
insert into tax_category (id, name, description) values (6, 'Lotus Root', 'Praesent id massa id nisl venenatis lacinia.');
insert into tax_category (id, name, description) values (7, 'Wine - White, Concha Y Toro', 'Curabitur gravida nisi at nibh.');
insert into tax_category (id, name, description) values (8, 'Skirt - 29 Foot', 'Suspendisse potenti.');
insert into tax_category (id, name, description) values (9, 'Longos - Penne With Pesto', 'Morbi non lectus.');
insert into tax_category (id, name, description) values (10, 'Pheasants - Whole', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
insert into tax_category (id, name, description) values (11, 'Paste - Black Olive', 'Suspendisse accumsan tortor quis turpis.');
insert into tax_category (id, name, description) values (12, 'Capers - Pickled', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.');
insert into tax_category (id, name, description) values (13, 'Crackers Cheez It', 'Vestibulum ac est lacinia nisi venenatis tristique.');
insert into tax_category (id, name, description) values (14, 'Yogurt - French Vanilla', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.');
insert into tax_category (id, name, description) values (15, 'Towel Multifold', 'Vestibulum sed magna at nunc commodo placerat.');
insert into tax_category (id, name, description) values (16, 'Juice - Orange 1.89l', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
insert into tax_category (id, name, description) values (17, 'Pomegranates', 'Nulla tempus.');
insert into tax_category (id, name, description) values (18, 'Coffee - Egg Nog Capuccino', 'Ut tellus.');
insert into tax_category (id, name, description) values (19, 'Pumpkin', 'Nulla tellus.');
insert into tax_category (id, name, description) values (20, 'Milk - 2%', 'Aliquam erat volutpat.');
insert into tax_category (id, name, description) values (21, 'Coconut - Shredded, Unsweet', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into tax_category (id, name, description) values (22, 'Cookie - Dough Variety', 'Nullam porttitor lacus at turpis.');
insert into tax_category (id, name, description) values (23, 'Tray - 12in Rnd Blk', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.');
insert into tax_category (id, name, description) values (24, 'Yukon Jack', 'Donec vitae nisi.');
insert into tax_category (id, name, description) values (25, 'Muffin Puck Ww Carrot', 'Pellentesque at nulla.');
insert into tax_category (id, name, description) values (26, 'Veal - Round, Eye Of', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.');
insert into tax_category (id, name, description) values (27, 'Lamb - Racks, Frenched', 'Praesent lectus.');
insert into tax_category (id, name, description) values (28, 'Towel - Roll White', 'Morbi vel lectus in quam fringilla rhoncus.');
insert into tax_category (id, name, description) values (29, 'Chickhen - Chicken Phyllo', 'Vestibulum sed magna at nunc commodo placerat.');
insert into tax_category (id, name, description) values (30, 'Pork - Loin, Bone - In', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.');
insert into tax_category (id, name, description) values (31, 'Bread - Roll, Canadian Dinner', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into tax_category (id, name, description) values (32, 'Magnotta Bel Paese Red', 'Morbi quis tortor id nulla ultrices aliquet.');
insert into tax_category (id, name, description) values (33, 'Muffin Mix - Raisin Bran', 'Aenean auctor gravida sem.');
insert into tax_category (id, name, description) values (34, 'Sobe - Orange Carrot', 'Vestibulum rutrum rutrum neque.');
insert into tax_category (id, name, description) values (35, 'Grapefruit - White', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.');
insert into tax_category (id, name, description) values (36, 'Rum - Cream, Amarula', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.');
insert into tax_category (id, name, description) values (37, 'Nescafe - Frothy French Vanilla', 'Aenean fermentum.');
insert into tax_category (id, name, description) values (38, 'Plate - Foam, Bread And Butter', 'Sed accumsan felis.');
insert into tax_category (id, name, description) values (39, 'Potatoes - Instant, Mashed', 'Fusce consequat.');
insert into tax_category (id, name, description) values (40, 'Pasta - Lasagne, Fresh', 'Donec posuere metus vitae ipsum.');
insert into tax_category (id, name, description) values (41, 'Papayas', 'Vivamus in felis eu sapien cursus vestibulum.');
insert into tax_category (id, name, description) values (42, 'Energy Drink - Franks Original', 'In congue.');
insert into tax_category (id, name, description) values (43, 'Pineapple - Golden', 'Vivamus vestibulum sagittis sapien.');
insert into tax_category (id, name, description) values (44, 'Chicken - Breast, 5 - 7 Oz', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.');
insert into tax_category (id, name, description) values (45, 'Ham - Cooked', 'Nulla mollis molestie lorem.');
insert into tax_category (id, name, description) values (46, 'Flour - Rye', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
insert into tax_category (id, name, description) values (47, 'Sambuca - Opal Nera', 'Suspendisse ornare consequat lectus.');
insert into tax_category (id, name, description) values (48, 'Orange Roughy 4/6 Oz', 'Sed sagittis.');
insert into tax_category (id, name, description) values (49, 'Broom - Push', 'Maecenas rhoncus aliquam lacus.');
insert into tax_category (id, name, description) values (50, 'Paper Towel Touchless', 'Nullam varius.');
insert into tax_category (id, name, description) values (51, 'Horseradish Root', 'Suspendisse ornare consequat lectus.');
insert into tax_category (id, name, description) values (52, 'Beef - Prime Rib Aaa', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.');
insert into tax_category (id, name, description) values (53, 'Canadian Emmenthal', 'Nunc rhoncus dui vel sem.');
insert into tax_category (id, name, description) values (54, 'Beef - Tongue, Cooked', 'In hac habitasse platea dictumst.');
insert into tax_category (id, name, description) values (55, 'Pasta - Ravioli', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.');
insert into tax_category (id, name, description) values (56, 'Iced Tea - Lemon, 340ml', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.');
insert into tax_category (id, name, description) values (57, 'Cheese - Wine', 'Mauris lacinia sapien quis libero.');
insert into tax_category (id, name, description) values (58, 'Bread - Burger', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into tax_category (id, name, description) values (59, 'Rice Paper', 'Suspendisse ornare consequat lectus.');
insert into tax_category (id, name, description) values (60, 'Crawfish', 'Nunc rhoncus dui vel sem.');
insert into tax_category (id, name, description) values (61, 'Soup - Chicken And Wild Rice', 'In blandit ultrices enim.');
insert into tax_category (id, name, description) values (62, 'French Pastries', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.');
insert into tax_category (id, name, description) values (63, 'Five Alive Citrus', 'In quis justo.');
insert into tax_category (id, name, description) values (64, 'Cookie Dough - Chunky', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.');
insert into tax_category (id, name, description) values (65, 'Wine - Jaboulet Cotes Du Rhone', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.');
insert into tax_category (id, name, description) values (66, 'Muffin - Mix - Mango Sour Cherry', 'Duis at velit eu est congue elementum.');
insert into tax_category (id, name, description) values (67, 'Island Oasis - Strawberry', 'Sed sagittis.');
insert into tax_category (id, name, description) values (68, 'Yogurt - Peach, 175 Gr', 'Cras non velit nec nisi vulputate nonummy.');
insert into tax_category (id, name, description) values (69, 'Cleaner - Lime Away', 'Nulla justo.');
insert into tax_category (id, name, description) values (70, 'Miso Paste White', 'Suspendisse accumsan tortor quis turpis.');
insert into tax_category (id, name, description) values (71, 'Sugar - Fine', 'Donec semper sapien a libero.');
insert into tax_category (id, name, description) values (72, 'Ecolab Silver Fusion', 'Suspendisse potenti.');
insert into tax_category (id, name, description) values (73, 'Yucca', 'Maecenas pulvinar lobortis est.');
insert into tax_category (id, name, description) values (74, 'Beef - Baby, Liver', 'Aenean lectus.');
insert into tax_category (id, name, description) values (75, 'Soup Bowl Clear 8oz92008', 'Mauris lacinia sapien quis libero.');
insert into tax_category (id, name, description) values (76, 'Amarula Cream', 'Pellentesque at nulla.');
insert into tax_category (id, name, description) values (77, 'Sugar - Icing', 'Morbi non lectus.');
insert into tax_category (id, name, description) values (78, 'Cheese - Gouda Smoked', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into tax_category (id, name, description) values (79, 'Lemon Balm - Fresh', 'In hac habitasse platea dictumst.');
insert into tax_category (id, name, description) values (80, 'Juice - Pineapple, 341 Ml', 'In blandit ultrices enim.');
insert into tax_category (id, name, description) values (81, 'Wine - Bouchard La Vignee Pinot', 'Nullam molestie nibh in lectus.');
insert into tax_category (id, name, description) values (82, 'Chives - Fresh', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.');
insert into tax_category (id, name, description) values (83, 'Wine - Touraine Azay - Le - Rideau', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.');
insert into tax_category (id, name, description) values (84, 'Soup - Knorr, French Onion', 'Maecenas rhoncus aliquam lacus.');
insert into tax_category (id, name, description) values (85, 'Wine - Red, Lurton Merlot De', 'Ut at dolor quis odio consequat varius.');
insert into tax_category (id, name, description) values (86, 'Wine - Cousino Macul Antiguas', 'Morbi vel lectus in quam fringilla rhoncus.');
insert into tax_category (id, name, description) values (87, 'Blueberries - Frozen', 'Duis bibendum.');
insert into tax_category (id, name, description) values (88, 'Lamb Tenderloin Nz Fr', 'Fusce consequat.');
insert into tax_category (id, name, description) values (89, 'Water, Tap', 'Mauris ullamcorper purus sit amet nulla.');
insert into tax_category (id, name, description) values (90, 'Cranberries - Frozen', 'Ut at dolor quis odio consequat varius.');
insert into tax_category (id, name, description) values (91, 'Chicken - Leg, Boneless', 'Curabitur in libero ut massa volutpat convallis.');
insert into tax_category (id, name, description) values (92, 'Oranges - Navel, 72', 'Nam tristique tortor eu pede.');
insert into tax_category (id, name, description) values (93, 'Sage Derby', 'Donec posuere metus vitae ipsum.');
insert into tax_category (id, name, description) values (94, 'V8 - Vegetable Cocktail', 'Vestibulum sed magna at nunc commodo placerat.');
insert into tax_category (id, name, description) values (95, 'Chocolate Bar - Smarties', 'Aliquam sit amet diam in magna bibendum imperdiet.');
insert into tax_category (id, name, description) values (96, 'Beans - Fava Fresh', 'Quisque ut erat.');
insert into tax_category (id, name, description) values (97, 'Wine - Champagne Brut Veuve', 'Integer tincidunt ante vel ipsum.');
insert into tax_category (id, name, description) values (98, 'Shrimp - 31/40', 'Mauris ullamcorper purus sit amet nulla.');
insert into tax_category (id, name, description) values (99, 'Carbonated Water - Blackcherry', 'In congue.');
insert into tax_category (id, name, description) values (100, 'Cucumber - Pickling Ontario', 'Donec quis orci eget orci vehicula condimentum.');
