insert into uom (id, name, description) values (1, 'ELC', 'Praesent blandit.');
insert into uom (id, name, description) values (2, 'JDD', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.');
insert into uom (id, name, description) values (3, 'DVD', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.');
insert into uom (id, name, description) values (4, 'IDTI', 'Suspendisse accumsan tortor quis turpis.');
insert into uom (id, name, description) values (5, 'HRI', 'Proin eu mi.');
insert into uom (id, name, description) values (6, 'POST', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.');
insert into uom (id, name, description) values (7, 'CUZ', 'Proin interdum mauris non ligula pellentesque ultrices.');
insert into uom (id, name, description) values (8, 'KBWB', 'Quisque ut erat.');
insert into uom (id, name, description) values (9, 'ANET', 'Curabitur gravida nisi at nibh.');
insert into uom (id, name, description) values (10, 'FWONK', 'Proin interdum mauris non ligula pellentesque ultrices.');
insert into uom (id, name, description) values (11, 'JCAP', 'In congue.');
insert into uom (id, name, description) values (12, 'MLCO', 'Cras non velit nec nisi vulputate nonummy.');
insert into uom (id, name, description) values (13, 'IESC', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into uom (id, name, description) values (14, 'CLIR', 'Nunc rhoncus dui vel sem.');
insert into uom (id, name, description) values (15, 'FPT', 'Morbi a ipsum.');
insert into uom (id, name, description) values (16, 'BNCL', 'Ut tellus.');
insert into uom (id, name, description) values (17, 'ALOG', 'Sed vel enim sit amet nunc viverra dapibus.');
insert into uom (id, name, description) values (18, 'CGNT', 'Nulla ut erat id mauris vulputate elementum.');
insert into uom (id, name, description) values (19, 'CORT', 'Integer ac neque.');
insert into uom (id, name, description) values (20, 'SPAN', 'In hac habitasse platea dictumst.');
insert into uom (id, name, description) values (21, 'RPAI', 'Duis bibendum.');
insert into uom (id, name, description) values (22, 'CTDD', 'Curabitur at ipsum ac tellus semper interdum.');
insert into uom (id, name, description) values (23, 'HEAR', 'Phasellus in felis.');
insert into uom (id, name, description) values (24, 'VLO', 'Fusce posuere felis sed lacus.');
insert into uom (id, name, description) values (25, 'FTD', 'Vivamus vel nulla eget eros elementum pellentesque.');
insert into uom (id, name, description) values (26, 'CDR^B', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into uom (id, name, description) values (27, 'CMRE^D', 'Proin risus.');
insert into uom (id, name, description) values (28, 'ALSK', 'Aliquam sit amet diam in magna bibendum imperdiet.');
insert into uom (id, name, description) values (29, 'NMZ', 'Quisque porta volutpat erat.');
insert into uom (id, name, description) values (30, 'FMSA', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.');
insert into uom (id, name, description) values (31, 'SOV^C', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into uom (id, name, description) values (32, 'YRCW', 'Etiam justo.');
insert into uom (id, name, description) values (33, 'IPDN', 'Maecenas ut massa quis augue luctus tincidunt.');
insert into uom (id, name, description) values (34, 'VTA', 'Etiam pretium iaculis justo.');
insert into uom (id, name, description) values (35, 'NBL', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.');
insert into uom (id, name, description) values (36, 'CGNT', 'Ut at dolor quis odio consequat varius.');
insert into uom (id, name, description) values (37, 'CSL', 'Duis at velit eu est congue elementum.');
insert into uom (id, name, description) values (38, 'OMER', 'Sed ante.');
insert into uom (id, name, description) values (39, 'AXP', 'Nullam varius.');
insert into uom (id, name, description) values (40, 'HDS', 'Curabitur gravida nisi at nibh.');
insert into uom (id, name, description) values (41, 'TIG', 'Aenean fermentum.');
insert into uom (id, name, description) values (42, 'LMFA', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into uom (id, name, description) values (43, 'LXFT', 'Etiam vel augue.');
insert into uom (id, name, description) values (44, 'UNF', 'Nulla facilisi.');
insert into uom (id, name, description) values (45, 'VLRS', 'Nam tristique tortor eu pede.');
insert into uom (id, name, description) values (46, 'NEFF', 'Nullam sit amet turpis elementum ligula vehicula consequat.');
insert into uom (id, name, description) values (47, 'WING', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into uom (id, name, description) values (48, 'FFIN', 'Proin risus.');
insert into uom (id, name, description) values (49, 'NTC', 'Sed vel enim sit amet nunc viverra dapibus.');
insert into uom (id, name, description) values (50, 'SCAC', 'Vivamus tortor.');
insert into uom (id, name, description) values (51, 'GNMK', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.');
insert into uom (id, name, description) values (52, 'HEI', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into uom (id, name, description) values (53, 'HUNT', 'Morbi ut odio.');
insert into uom (id, name, description) values (54, 'FRC^H', 'Phasellus id sapien in sapien iaculis congue.');
insert into uom (id, name, description) values (55, 'PXS', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
insert into uom (id, name, description) values (56, 'FGP', 'Quisque id justo sit amet sapien dignissim vestibulum.');
insert into uom (id, name, description) values (57, 'TRVN', 'Donec vitae nisi.');
insert into uom (id, name, description) values (58, 'WIW', 'Morbi non quam nec dui luctus rutrum.');
insert into uom (id, name, description) values (59, 'ING', 'Cras pellentesque volutpat dui.');
insert into uom (id, name, description) values (60, 'GS^A', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.');
insert into uom (id, name, description) values (61, 'MTSC', 'Cras non velit nec nisi vulputate nonummy.');
insert into uom (id, name, description) values (62, 'ITCI', 'Donec semper sapien a libero.');
insert into uom (id, name, description) values (63, 'UAA', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.');
insert into uom (id, name, description) values (64, 'ZF', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.');
insert into uom (id, name, description) values (65, 'AFSI^C', 'Curabitur gravida nisi at nibh.');
insert into uom (id, name, description) values (66, 'KMI', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.');
insert into uom (id, name, description) values (67, 'UCFC', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.');
insert into uom (id, name, description) values (68, 'AIB', 'Duis at velit eu est congue elementum.');
insert into uom (id, name, description) values (69, 'VLGEA', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
insert into uom (id, name, description) values (70, 'CECE', 'Vivamus in felis eu sapien cursus vestibulum.');
insert into uom (id, name, description) values (71, 'ADRU', 'Praesent blandit lacinia erat.');
insert into uom (id, name, description) values (72, 'MCHX', 'Suspendisse potenti.');
insert into uom (id, name, description) values (73, 'EAE', 'Ut at dolor quis odio consequat varius.');
insert into uom (id, name, description) values (74, 'EE', 'Aliquam erat volutpat.');
insert into uom (id, name, description) values (75, 'FSS', 'Curabitur gravida nisi at nibh.');
insert into uom (id, name, description) values (76, 'LTM', 'Integer tincidunt ante vel ipsum.');
insert into uom (id, name, description) values (77, 'AP', 'Suspendisse potenti.');
insert into uom (id, name, description) values (78, 'BWG', 'Nulla facilisi.');
insert into uom (id, name, description) values (79, 'OB', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.');
insert into uom (id, name, description) values (80, 'GCV', 'Proin at turpis a pede posuere nonummy.');
insert into uom (id, name, description) values (81, 'TRST', 'Duis at velit eu est congue elementum.');
insert into uom (id, name, description) values (82, 'GPIC', 'Maecenas rhoncus aliquam lacus.');
insert into uom (id, name, description) values (83, 'SALT', 'Praesent blandit.');
insert into uom (id, name, description) values (84, 'DIAX', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.');
insert into uom (id, name, description) values (85, 'JRS', 'Nulla tempus.');
insert into uom (id, name, description) values (86, 'FSIC', 'Nulla ac enim.');
insert into uom (id, name, description) values (87, 'RTTR', 'Aenean lectus.');
insert into uom (id, name, description) values (88, 'KFFB', 'Suspendisse potenti.');
insert into uom (id, name, description) values (89, 'APPS', 'Mauris lacinia sapien quis libero.');
insert into uom (id, name, description) values (90, 'AEZS', 'In hac habitasse platea dictumst.');
insert into uom (id, name, description) values (91, 'PACB', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into uom (id, name, description) values (92, 'ZGNX', 'Ut at dolor quis odio consequat varius.');
insert into uom (id, name, description) values (93, 'CBS.A', 'Nullam porttitor lacus at turpis.');
insert into uom (id, name, description) values (94, 'CALI', 'Morbi a ipsum.');
insert into uom (id, name, description) values (95, 'CVI', 'Phasellus sit amet erat.');
insert into uom (id, name, description) values (96, 'RFEM', 'Duis at velit eu est congue elementum.');
insert into uom (id, name, description) values (97, 'SGEN', 'Morbi porttitor lorem id ligula.');
insert into uom (id, name, description) values (98, 'PTI', 'Sed sagittis.');
insert into uom (id, name, description) values (99, 'C', 'Praesent blandit lacinia erat.');
insert into uom (id, name, description) values (100, 'XNCR', 'Suspendisse potenti.');
